version: '3.8'

services:
  db:
    build:
      context: ./project/db
    container_name: region_pricing_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ratestask
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: ./project
    container_name: region_pricing_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data:
